# Generated by Django 5.0.4 on 2024-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="total_unique_words",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="total_words",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
